services:
  nodeapp:
    build: .
    container_name: my_node_app
    environment:
      PORT: 5000
      mongodb_url: mongodb://admin:Admin%40123@127.0.0.1:27017/export_data?authSource=admin
      REDIS_HOST: redis
      REDIS_PORT: 6379
      EXPORT_SCHEDULING_MODE: immediate
      EXPORT_SCHEDULE_HOUR: 10
      EXPORT_SCHEDULE_MINUTE: 0
    command: npm run dev
    ports:
      - "3000:3000"
      - "9229:9229"
    volumes:
      - ./exports:/app/exports
      - .:/app
    network_mode: host

